spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#  disable service discovery, false si ce n'est pas encore défini
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://${DISCOVERY_URL:localhost:8761/eureka}

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
eureka.instance.prefer-ip-address=true


